<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppHost\AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.3.1" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.*" />
    <PackageReference Include="AWSSDK.ECS" Version="3.*" />
    <PackageReference Include="AWSSDK.EventBridge" Version="3.*" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.*" />
    <PackageReference Include="AWSSDK.RDS" Version="3.*" />
    <PackageReference Include="AWSSDK.S3" Version="3.*" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.*" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.*" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.*" />
    <PackageReference Include="AWSSDK.SQS" Version="3.*" />
    <PackageReference Include="AWSSDK.Scheduler" Version="3.*" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.*" />
    <PackageReference Include="AWSSDK.StepFunctions" Version="3.*" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

</Project>
